VALID_PARAMETERS = {'aoo': ['lower_rate_limit',
                            'upper_rate_limit',
                            'atrial_amplitude',
                            'atrial_pw'],
                    'voo': ['lower_rate_limit',
                            'upper_rate_limit',
                            'ventricular_amplitude', 
                            'ventricular_pw'],
                    'aai': ['lower_rate_limit', 
                            'upper_rate_limit', 
                            'atrial_amplitude', 
                            'atrial_pw', 
                            'arp'],
                    'vvi': ['lower_rate_limit', 
                            'upper_rate_limit', 
                            'ventricular_amplitude', 
                            'ventricular_pw',
                            'vrp'],
                    'doo': ['lower_rate_limit',
                            'upper_rate_limit',
                            'fixed_av_delay',
                            'atrial_amplitude',
                            'ventricular_amplitude',
                            'atrial_pw',
                            'ventricular_pw'],
                    'aoor': ['lower_rate_limit',
                             'upper_rate_limit',
                             'max_sensor_rate',
                             'atrial_amplitude',
                             'atrial_pw',
                             'activity_threshold',
                             'reaction_time',
                             'response_factor',
                             'recovery_time'],
                    'voor': ['lower_rate_limit',
                             'upper_rate_limit',
                             'max_sensor_rate',
                             'ventricular_amplitude',
                             'ventricular_pw',
                             'activity_threshold',
                             'reaction_time',
                             'response_factor',
                             'recovery_time'],
                    'aair': ['lower_rate_limit',
                             'upper_rate_limit',
                             'max_sensor_rate',
                             'atrial_amplitude',
                             'atrial_pw',
                             'atrial_sensitivity',
                             'arp',
                             'pvarp',
                             'hysteresis',
                             'rate_smoothing',
                             'activity_threshold',
                             'reaction_time',
                             'response_factor',
                             'recovery_time'],
                    'vvir': ['lower_rate_limit',
                             'upper_rate_limit',
                             'max_sensor_rate',
                             'ventricular_amplitude',
                             'ventricular_pw',
                             'ventricular_sensitivity',
                             'vrp',
                             'hysteresis',
                             'rate_smoothing',
                             'activity_threshold',
                             'reaction_time',
                             'response_factor',
                             'recovery_time'],
                    'door': ['lower_rate_limit',
                             'upper_rate_limit',
                             'fixed_av_delay',
                             'max_sensor_rate',
                             'atrial_amplitude',
                             'ventricular_amplitude',
                             'atrial_pw',
                             'ventricular_pw',
                             'activity_threshold',
                             'reaction_time',
                             'response_factor',
                             'recovery_time']}
